### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by Deathorn** [p-e-w/argos#2]
Hi, awesome extension!

1. How does ```dropdown``` attribute work? I thought it should hide dropdown menu and just output result. But I always can click on button and get dropdown menu with the name of the script. I use it like this
```
#!/bin/bash

echo "test | dropdown=false"
```
Is this correct?

2. The name of the script is always visible in dropdown menu, can it be hidden?

Thank you for extension! :)

**Comment by p-e-w** [comment]
> How does `dropdown` attribute work?

The same way it does in BitBar. If there are multiple "button lines" (lines before the first separator), *two* things happen: The button cycles between them every 3 seconds, and a dropdown menu item is created for each.

Setting the `dropdown` attribute to `false` on a line skips the second part and no dropdown item is created for the line. To do the reverse and create a dropdown item without cycling the line in the button, just place it after the first separator.

The widget added to the panel is a dropdown menu button, so disabling the menu entirely doesn't really make sense. The dropdown menu is hidden by default – if you don't want to see it, I guess the "fix" is to simply not click on the button.

> The name of the script is always visible in dropdown menu, can it be hidden?

Not currently, no. Clicking on the name brings up the script in a text editor, where it can be live-edited which is a very convenient feature. The problem with making this configurable is that it is an attribute of the entire plugin, not of any particular output line. The only way to add plugin-level configuration options is to put them in the filename, and the format is already complicated enough so I don't want to extend it without a very good reason.

BitBar actually has the same issue, except that it adds *five* additional items to each dropdown menu instead of just one. The way plugins work limits global configurability, which is the flip side of how easy they are to use.

**Comment by jhasse** [comment]
Displaying the script name could be disabled for all scripts in argos' GNOME Shell setting.

**Comment by zeten30** [comment]
Hi @jhasse , where exactly I can disable it. I see no dconf/gconf values for argos. Thanks in advance.

**Comment by jhasse** [comment]
@zeten30 It was just a suggestion how it *could* be done. Currently you can't disable it AFAIK.
