### ISSUE TITLE
How can I call a bash function?

### ISSUE THREAD

**Issue by bill-mavromatis** [p-e-w/argos#21]
Hi, awesome project!
I'm trying to port my bash script to argos and I may be missing something obvious, but how can I call a function in argos? For example:

myfunc () { echo test ; }

echo "Option1 | iconName=gedit bash='myfunc' terminal=true"
echo "---"

and I get no output (just a terminal opens). I tried playing around with commands but couldn't get anywhere.

**Comment by p-e-w** [comment]
The problem is that you are declaring `myfunc` in your script and then launching a separate instance of Bash expecting the function to be defined there.

You can try adding

```
export -f myfunc
```

which is what you would do to make `myfunc` available to subshells, but even that is unlikely to work because the "subshell" is not hosted by your Bash instance but by a newly spawned terminal process.

The only way that is sure to work is to make the function declaration part of the `bash` parameter value. To avoid long lines in your script, you can put that part in a variable and expand it in the `echo` string.

**Comment by WhiteheadV** [comment]
Interpreting p-e-w's comment on this closed issue which has also troubled me b4, and using the example 4rm the issue you @bill-mavromatis opened, I made a demo of the second solution p-e-w proposed:
> The only way that is sure to work is to make the function declaration part of the bash parameter value. To avoid long lines in your script, you can put that part in a variable and expand it in the echo string.
> - @p-e-w 
```bash
#!/bin/bash

myfunc () { echo echo "I echo this when called, now..make me do stuff..." ; }

var=$(myfunc)

echo "Option1 | iconName=gedit-symbolic"
echo "---"
echo "Saving the func to a var then calling it -> | bash='$var' terminal=true"
echo '--'
echo "Directly calling the function -> | bash='$(myfunc)' terminal=true"
```
