### ISSUE TITLE
Image instead of icon

### ISSUE THREAD

**Issue by GrouchyGaijin** [p-e-w/argos#3]
First of all, thank you!  I have been wondering if there is an easy way to add a launcher to the top of the Gnome Shell.

I am having trouble with the image tag.  I can get a launcher entry to show an icon if I choose an icon from an installed program, but am not able to use a custom image as an icon.
I tried specifying the path to the iimage file I want to use, but it still does not show up.

Any advice?

**Comment by jhasse** [comment]
You can put the icon in `/usr/share/icons` yourself and use it's basename :)

**Comment by p-e-w** [comment]
The `image` attribute expects not a path but a Base64-encoded image file (see the "Value" column [here](https://github.com/p-e-w/argos#display)).

This is first and foremost because that's what BitBar does (which Argos aims to be compatible with), but also has the advantage that it allows images to be embedded in the shell script, making scripts self-contained.

There is actually an example demonstrating use of the `image` attribute [in the README](https://github.com/p-e-w/argos#launchersh). When using the `base64` command line tool, be sure to always add `-w 0` as an argument to disable wrapping.
