### ISSUE TITLE
Multiple mutt profiles

### ISSUE THREAD

**Issue by GrouchyGaijin** [p-e-w/argos#41]
I use Mutt as my email client. I have two email accounts. I can add my main account to argos with this:
`echo "Mutt | iconName=dog bash=/home/john/scripts/jfn-mutt terminal=true"
`
The bash script for this is simply:
`#!/bin/bash`
`mutt`
In my bash aliases file I have this to launch my second profile:
`alias jmutt='mutt -F ~/.mutt/profile.john`
This works when I type the alias in a terminal.
In argos I added `echo "JMutt | iconName=dog bash=/home/john/scripts/johnmutt terminal=true"`
I tried making a bash script to call this second profile from argos with this code:
`#!/bin/bash`
`mutt -F ~/.mutt/profile.john`
However, this results in my main account being opened.
Any idea on how I can fix this so that argos will open my second email account in Mutt?

**Comment by p-e-w** [comment]
While I know nothing about Mutt, it seems clear that whatever is going on here must be an issue with that program, the shell, or your environment. Argos does a simple process launch, that's all.

Please feel free to reopen this issue if you have reason to believe that the problem lies indeed with Argos itself, rather than another factor out of its control.
