### ISSUE TITLE
Possibly an easier way to load images async? 

### ISSUE THREAD

**Issue by JasonLG1979** [p-e-w/argos#6]
I was reading through your source code and I came across this:
https://github.com/p-e-w/argos/blob/master/argos%40pew.worldwidemann.com/lineview.js#L44-L82

I'm not exactly sure what image is? But if it's an image uri there's a much easier way to do it.

I was looking for a way myself to load remote images async with error checking for:
 https://github.com/eonpatapon/gnome-shell-extensions-mediaplayer

And this is what I came up with:
```js
function setCoverIconAsync(icon, coverUrl, fallback_icon_name) {
  let file = Gio.File.new_for_uri(coverUrl);
  file.load_contents_async(null, function(source, result) {
    try {
      let bytes = source.load_contents_finish(result)[1];
      icon.gicon = Gio.BytesIcon.new(bytes);
    }
    catch(err) {
      icon.icon_name = fallback_icon_name;
    }
  });
}
```

In our case we pass the cover icon we want to change a cover url(local or remote) and a fallback icon name in case we get an error.

Works like a charm for me. Again though I may be off base of what you're actually trying to do?

**Comment by p-e-w** [comment]
`image` is a Base64-encoded image file, not an image URI. The code has really nothing to do with asynchronous loading, but thanks for the input 😄

**Comment by JasonLG1979** [comment]
Right on. Another thing I noticed is this.
https://github.com/p-e-w/argos/blob/86e10edfe8c3e5d04af77f5e5e7aca18817b5cef/argos%40pew.worldwidemann.com/button.js#L168-L172

You can get around that by a little bit of subclassing and monkeypatching.
https://github.com/eonpatapon/gnome-shell-extensions-mediaplayer/blob/master/src/widget.js#L490-L610

**Comment by p-e-w** [comment]
Nice one, I was wondering whether someone had already implemented this themselves. 👍

I'm not going to add this though. This is a bug in GNOME Shell, not in Argos. It should be fixed in GNOME Shell. A one-liner workaround would probably be OK to add, but 120 lines of additional maintenance burden is another matter.

Have you considered upstreaming that code to GNOME Shell?

**Comment by JasonLG1979** [comment]
Agreed. As a toolkit or whatever you want to call it. GNOME Shell is pretty much crap...

**Comment by JasonLG1979** [comment]
> A one-liner workaround would probably be OK to add, but 120 lines of additional maintenance burden is another matter.

My subclasses are probably overkill for your needs. It does a bunch of stuff i need it to. If you don't need to to anything but stop children from closing their parents you can just monkeypatch the menu's emit method and make it just ignore the open-state-changed signal(I think that's what it is) and then monkeypatch the menu's open and close methods to emit your own signals if you want.

**Comment by JasonLG1979** [comment]
Be aware though that nested menus totally messes up scrollbars. They show up when they're not suppose to and don't when they are almost randomly. You could end up overflowing the screen or having menus that don't need scrollbars but have them anyway. The problem seems to be the animation so I disable animation in my menus.

**Comment by p-e-w** [comment]
> Be aware though that nested menus totally messes up scrollbars.

Yeah, I noticed that too. There is also another bug: When the menu already fills the screen height, clicking submenu headers doesn't open the submenus.

I love GNOME because of its amazing visual design. IMO, GNOME Shell is the single most beautiful desktop available today. It looks better than macOS, better than Windows, better than Plasma, Unity, MATE, Cinnamon... the clean appearance of both desktop and windows is as close to perfection as I've ever seen, even with everything left to its default settings.

However, it's hard to overlook GNOME's colossal shortcomings as a platform for developers. Breaking every single extension every six months for five years is a slap in the face for everyone that invested time creating an extension. Fortunately, this nonsense ends with GNOME 3.24 at last. Of course, there is still no proper API documentation for Gjs, among other problems.

**Comment by JasonLG1979** [comment]
> There is also another bug: When the menu already fills the screen height, clicking submenu headers doesn't open the submenus.

I don't see that as a bug. There just isn't any more room on the screen. Where is the menu suppose to open up to?

**Comment by p-e-w** [comment]
> I don't see that as a bug. There just isn't any more room on the screen. Where is the menu suppose to open up to?

Ideally the menu would scroll vertically, like the Bookmarks menu in Firefox. At a minimum, it should indicate visually that there are additional menu items that can't be displayed, perhaps with an ellipsis somewhere.

**Comment by JasonLG1979** [comment]
> Ideally the menu would scroll vertically, like the Bookmarks menu in Firefox. At a minimum, it should indicate visually that there are additional menu items that can't be displayed, perhaps with an ellipsis somewhere.

If it's nested the outer most menu will <b><i>try</i></b> to become scrolling but it requires some monkey patching for it to work correctly and you have to disable animation:
 https://github.com/eonpatapon/gnome-shell-extensions-mediaplayer/blob/master/src/widget.js#L561-L575
