### ISSUE TITLE
Gnome 3.32.0 Defunct?

### ISSUE THREAD

**Issue by lordSeaworth** [p-e-w/argos#75]
Not sure if this is the right place. But is it possible that this extension stopped working with latest gnome version?

**Comment by ebeem** [comment]
my extensions didn't work after the update, so I think 3.32 broke some APIs or something

**Comment by lordSeaworth** [comment]
Yeah. Seems so. Really hope this gets fixed soon. Love this extension.

**Comment by jakommo** [comment]
Just upgraded to Gnome 3.32.0 and the menu's do not open anymore when I click on an item.
Displaying results from the scripts still works fine for me. 

@lordSeaworth @ebeem is it not working at all for you or also just the menu not opening on click?

**Comment by jakommo** [comment]
Just tested https://github.com/p-e-w/argos/pull/76 and that fixed it for me and all my scripts started working again.

**Comment by p-e-w** [comment]
So, here is the whole sad story (thanks to @ccat3z for linking to the key issue from #76):

On January 15, the GNOME developers [decided](https://gitlab.gnome.org/GNOME/gnome-shell/merge_requests/350) to move from `Lang.Class` to ES6 classes, even though this "has the potential to break extensions" (no shit!).

On January 23, this change [was indeed made](https://gitlab.gnome.org/GNOME/gnome-shell/merge_requests/361).

On March 13, [GNOME 3.32 was released](https://www.gnome.org/news/2019/03/gnome-3-32-released/) with the change, breaking Argos (and presumably 80% of all other Shell Extensions as well).

From first relevant pull request to ecosystem-shattering stable release (in a minor version!) in *less than two months.*

No deprecation period, no shims, no outreach (that I'm aware of).

As a third party trying to develop for the GNOME platform, I have taken a lot of poor treatment from GNOME over the years, including them [breaking my other project Plotinus](https://github.com/p-e-w/plotinus/issues/35), breaking *all* Shell Extensions on every single GNOME release for years, breaking themes again and again, and the complete absence of official, reliable documentation for large parts of the platform.

It appears that GNOME is either unwilling or unable to provide any sort of stability for the GNOME developer experience, even 8 years and 17 consecutive stable releases after the original GNOME 3.

As painful as this is, at some point, I have to draw a line. **I will no longer be developing for the GNOME platform, effective immediately.** This includes all development on the Argos extension.

This is not a decision I am making lightly. I have been pondering it ever since this issue was originally brought to my attention a week ago. But the simple truth is that I don't want to spend time building things for an ecosystem whose maintainers are willing to break my work on a whim, and unwilling to make any guarantees to the contrary.

I intend to move from GNOME to [sway](https://github.com/swaywm/sway) in the near future, a promising project that I have been following for a while and whose maintainers have demonstrated that they understand essential concepts like Semantic Versioning and the importance of platform stability. If ever I return to Desktop Linux development, it will most likely be within the sway ecosystem.

I am aware that many people use Argos and find it useful (I use it myself every day). Even though I will not be writing code for Argos anymore, **I will continue to review and merge pull requests, and occasionally release a new version on extensions.gnome.org.** Therefore, if there is enough community interest, Argos can live on. If someone were to show sufficient engagement, I might even be willing to grant them write access to this repository so things can move faster, as I won't be prioritizing Argos requests anymore.

It is encouraging to see that for this issue, there is already a community-provided fix in the works in the form of #76.

**Comment by timenz** [comment]
Fully respect for your decision @p-e-w , thank for your great work.

**Comment by p-e-w** [comment]
Fixed by @ccat3z in #76.
