### ISSUE TITLE
Global app menu

### ISSUE THREAD

**Issue by kukuri666** [p-e-w/argos#9]
is it possible to create something like global app menu with argos?

**Comment by p-e-w** [comment]
Not sure what you mean... can you give more details or an example/screenshot of what you want to create?

**Comment by kukuri666** [comment]
like the global app menu on unity or mac os
![java-globalmenu-netbeans](https://cloud.githubusercontent.com/assets/26411838/24323624/f4e4e690-11aa-11e7-9a3f-22bcca54a1f0.png)

**Comment by p-e-w** [comment]
That would be difficult to do with Argos because you would want to react when the foreground application changes, while Argos plugins are either static or refresh at a fixed time interval.

Incidentally, have you seen my project [Plotinus](https://github.com/p-e-w/plotinus)? It's something like a (searchable) global menu for GTK+ 3.
